---
name: "Build"

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  build:
    name: "Java"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        java-version: ["21"]

    steps:
      - uses: "actions/checkout@v5"

      - uses: "actions/setup-java@v5"
        with:
          distribution: "temurin"
          java-version: "${{ matrix.java-version }}"

      - run: "mvn -B --fail-fast clean verify"


